# このDockerfileは初期セットアップで一回実行するためだけに使用する。
# チームに展開するDockerfileとは異なります。

# Node.js 18を使用
FROM node:18

# 作業ディレクトリを設定
WORKDIR /frontend

# 最新バージョンのnpmをインストール
RUN npm install -g npm@latest

# Reactプロジェクトを作成
RUN npx create-react-app react_project