export { SetupPage } from './SetupPage'
export { PlayersInputPage } from './PlayersInputPage'
export { PlayerMessagesPage } from './PlayerMessagesPage'
export { TalkStartPage} from './TalkStartPage'
export { TransactionPage } from './TransactionPage'
export { ProviderPage } from './ProviderPage' 
export { TalkEndPage } from './TalkEndPage'
export { ResultsPage } from './ResultsPage'
export { ConfirmationCompletePage } from './ConfirmationCompletePage'